"""added review rlshp to borrowers

Revision ID: 581979d05e71
Revises: b15c17c6c810
Create Date: 2023-06-09 11:01:10.543225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '581979d05e71'
down_revision = 'b15c17c6c810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
