"""add realationship between book and reviews

Revision ID: b15c17c6c810
Revises: e2a091762ab3
Create Date: 2023-06-09 10:42:35.995175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b15c17c6c810'
down_revision = 'e2a091762ab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
