"""create borrowers and reviews tables

Revision ID: e4cd466276e9
Revises: 3733f8493247
Create Date: 2023-06-09 10:04:32.945549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4cd466276e9'
down_revision = '3733f8493247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
